DROP TABLE IF EXISTS AuditLog;
DROP TABLE IF EXISTS Alert;
DROP TABLE IF EXISTS Holdings;
DROP TABLE IF EXISTS PriceHistory;
DROP TABLE IF EXISTS Portfolio;
DROP TABLE IF EXISTS Ticker;
DROP TABLE IF EXISTS User;